# Generated by Django 3.0.5 on 2020-06-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('END', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='she',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('us', models.CharField(max_length=10)),
                ('pwd', models.CharField(max_length=10)),
            ],
        ),
    ]
